{ id: 35,
    txid: '6dbdd552bed6523a48de3d07dfbdb655cf8386582cb4e7b5e0a7090ebf80e9bc',
    BlockHeight: 68,
    'Vouts.id': null,
    'Vouts.n': null,
    'Vouts.value': null,
    'Vouts.TransactionVouts.direction': null,
    'Vouts.TransactionVouts.TransactionId': null,
    'Vouts.TransactionVouts.VoutId': null,
    'Vouts.Addresses.id': null,
    'Vouts.Addresses.address': null,
    'Vouts.Addresses.AddressVout.AddressId': null,
    'Vouts.Addresses.AddressVout.VoutId': null },